name: Scraper Diario

on:
  schedule:
    - cron: '0 9 * * *' # Cada día a las 9 AM UTC
  workflow_dispatch:    # Permite ejecutarlo manualmente desde la web

jobs:
  scraping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Configurar Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      
      - name: Instalar librerías
        run: |
          pip install -r requirements.txt
      
      - name: Ejecutar Scraping
        run: python main.py
