name: Scraper Diario

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

# 👇 AGREGA ESTO: Optar por Node.js 24 para todas las acciones
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  scraping:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Instalar librerías
        run: pip install -r requirements.txt
      
      - name: Ejecutar Scraping
        run: python main.py
      
      - name: Configurar Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
      
      - name: Guardar resultados en el repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add resultados.csv
          git commit -m 'Actualizar datos de scraping' || echo "Sin cambios nuevos"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
      
      - name: Subir Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: resultados-scraper-${{ github.run_number }}
          path: resultados.csv
          retention-days: 30
